commitMessage: "Prettify Code"

printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
jsxBracketSameLine: true
jsxSingleQuote: false
trailingComma: "es5"
bracketSpacing: true
arrowParens: "avoid"